title: Top3 Academy
description: Web3顶级学习平台 | 智能合约开发、链上交互和前端DApp开发实战教程，从入门到精通！
#baseurl: "/OnePolloWeb3"
# 采用自定义域名后不需要仓库名
baseurl: ""  # 留空，因为现在使用的是根域名
url: "https://learnweb3.top"  # 设置你的新域名

# 构建设置
markdown: kramdown

sass:
  sass_dir: assets/css
  style: compressed